# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('identifier', models.IntegerField(blank=True, null=True, verbose_name='Identificaci\xf3n')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('direction', models.CharField(max_length=255, verbose_name='Direcci\xf3n')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.IntegerField(verbose_name='Tel\xe9fono')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', related_query_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
