# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('frame_height', models.FloatField(verbose_name='Alto de marco')),
                ('frame_width', models.FloatField(verbose_name='Ancho de marco')),
                ('finished_height', models.FloatField(verbose_name='Alto terminado')),
                ('finished_width', models.FloatField(verbose_name='Ancho terminado')),
                ('installation', models.CharField(choices=[(0, 'Techo'), (1, 'Pared')], max_length=50, verbose_name='Instalaci\xf3n')),
                ('pipe', models.CharField(choices=[(0, '38mm'), (1, '45mm'), (2, '70mm')], max_length=50, verbose_name='Tubo')),
                ('weight', models.CharField(choices=[(0, 'Chato'), (1, 'Redondo')], max_length=50, verbose_name='Peso')),
                ('control', models.CharField(choices=[(0, 'Derecha'), (1, 'Izquierda')], max_length=50, verbose_name='Mando')),
                ('type', models.CharField(blank=True, max_length=500, verbose_name='Tipo de persiana')),
                ('fabric', models.CharField(blank=True, max_length=500, verbose_name='C\xf3digo de tela')),
                ('comment', models.CharField(blank=True, max_length=1000, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blids', related_query_name='blind', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
