# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_raise', '0002_auto_20170911_2304'),
        ('blind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blind',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blinds', related_query_name='blind', to='order_raise.OrderRaise'),
            preserve_default=False,
        ),
    ]
